jobs:
    include:
        - stage: e2e Test
          name: core
          before_script:
              - ./scripts/ci/job_hooks/before_e2e.sh
              - ./scripts/ci/check-env/check-cs-env.sh || travis_terminate 1
              - ./scripts/ci/check-env/check-ps-env.sh || travis_terminate 1
          script: ./scripts/travis/e2e/core-e2e.sh
          after_script: ./scripts/ci/job_hooks/after_e2e.sh

        - stage: e2e Test
          name:  content
          before_script:
              - ./scripts/ci/job_hooks/before_e2e.sh
              - ./scripts/ci/check-env/check-cs-env.sh || travis_terminate 1
          script: ./scripts/travis/e2e/content-services-e2e.sh
          after_script: ./scripts/ci/job_hooks/after_e2e.sh

        - stage: e2e Test
          name:  search
          before_script:
              - ./scripts/ci/job_hooks/before_e2e.sh
              - ./scripts/ci/check-env/check-cs-env.sh || travis_terminate 1
          script: ./scripts/travis/e2e/search-e2e.sh
          after_script: ./scripts/ci/job_hooks/after_e2e.sh

        - stage: e2e Test
          name: process
          before_script:
              - ./scripts/ci/job_hooks/before_e2e.sh || travis_terminate 1
              - ./scripts/ci/check-env/check-ps-env.sh || travis_terminate 1
          script: ./scripts/travis/e2e/process-services-e2e.sh
          after_script: ./scripts/ci/job_hooks/after_e2e.sh

        - stage: e2e Test
          name: process Cloud
          before_script:
              - ./scripts/ci/job_hooks/before_e2e.sh
              - ./scripts/ci/check-env/check-cs-env.sh || travis_terminate 1
              - ./scripts/ci/check-env/check-ps-cloud-env.sh || travis_terminate 1
          script: ./scripts/travis/e2e/process-services-cloud-e2e.sh
          after_script: ./scripts/ci/job_hooks/after_e2e.sh
